name: Hello Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  say-hello:
    runs-on: self-hosted # This specifies that the job runs on a self-hosted runner
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Say Hello
      run: echo "Hello"
